### ISSUE TITLE
Import function for Contacts not connected

### ISSUE THREAD

**Issue by asasin114** [itflow-org/itflow#464] opened 2022-05-12 16:13 UTC
**Describe the bug**
The link for the Import button on the Contacts section in a client does not work

**Can you reproduce this on the demo at demo.itflow.org**
Yes

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
1. Go to any random client
2. Click on Contacts
3. Click "Import"

**Expected behavior**
File upload box should appear for the import of a CSV file to import contacts but when looking through Dev Tools I see that the "href" tag points to "#" instead of an actual link. (see pic below for reference)

**Screenshots**
![image](https://user-images.githubusercontent.com/417006/168120198-c5cba679-496b-4f4c-9421-8b7189ea1f55.png)

This isn't super urgent but would be great to have. It would also be nice to have an option to import user lists from an Azure AD or allow clients to create an account and have it automatically assigned based on the domain they sign up with (example: User works for "Company X" and has an email of "username@companyx.com". They can create an account in the client portal which automatically adds the user to "Company X" in IT Flow). This would minimize the amount of time required to setup a new client.

**Comment by johnnyq** [comment] 2022-05-13 15:55
Hi @asasin114 the imports contact feature has been added 8b5f8547c49831496f995d13e504b19f4ce496e8

go ahead and update and let us know if it is working as intended on your side.

**Comment by johnnyq** [comment] 2022-05-13 16:20
okay the previous issue has been fixed

fdc42ef5cf6ddf546d62bf26ef1318c0d5362021

**Comment by asasin114** [comment] 2022-05-13 20:58
Working great! Thank you!

**Comment by johnnyq** [comment] 2022-05-13 21:11
Super! Thanks for reporting this issue to us. We will close this out now.

**Closed by johnnyq** 2022-05-13 21:11 UTC
Labels: enhancement
