### ISSUE TITLE
Bug/Feature Requests - Trips

### ISSUE THREAD

**Issue by Malcharias25** [itflow-org/itflow#176] opened 2021-03-18 17:26 UTC
A couple of items I noticed on the Trips panel:

- BUG: Import/Export options on the company Trips panel do not function - clicking on them provide either a white page (import) or an error page (export)
- FEATURE REQUEST: Ability to enter odometer start/end instead of raw trip mileage - it would also be handy to have the trip mileage automatically calculate based on the odometer entries.

**Comment by johnnyq** [comment] 2021-03-19 07:04
Yeah import and export is broken, i'm working on implementing that function everywhere
I will implement the odometer idea that makes sense and it will auto calculate too!!

**Comment by johnnyq** [comment] 2021-03-19 07:05
keep em coming all great ideas!!

**Comment by Malcharias25** [comment] 2021-03-22 22:57
@johnnyq I just found another (possible) bug in the Trips module.

It seems that the Technician role doesn't have access to be able to add trips under clients - is this as intended? I think this feature might be more useful if a technician can add their own trip information to a client without having to submit it to an accountant/admin.

**Comment by aftechro** [comment] 2021-03-24 12:29
Hey Johnny,

Did you update the zip or git resource?

For some reason i have same error on the trips like previous post.

Also, i`ve noticed that when first run, the currency on the dash board not changing as the one selected at the beginning. May be just the icon :D (euro)

**Comment by aftechro** [comment] 2021-03-24 12:34
think the issue is here:

![image](https://user-images.githubusercontent.com/38830718/112310780-dddd8080-8c9c-11eb-9c9d-a2e0a5f9d041.png)

 the date range need to be selected in order to display the data. otherwise wont be sown

![image](https://user-images.githubusercontent.com/38830718/112310927-05cce400-8c9d-11eb-902c-a2b685c99d35.png)

![image](https://user-images.githubusercontent.com/38830718/112310955-10877900-8c9d-11eb-8a74-3c4a7b198e28.png)

it doesn't bother me as i know the work around, but will be nice to have the previous data be visible without selecting the data range, and only use the date range when needed.

Thanks!

**Comment by johnnyq** [comment] 2021-03-25 02:07
Hi @aftechro I did update the it although the DB structure has changed as well which should fix the errors you are seeing give it a reinstall and let me know

**Comment by aftechro** [comment] 2021-03-25 20:17
Yeah, leave it with me, cause i`ve done both git clone and zip download and fresh new db with same result. i`ll check few things and let you know. Thanks!

**Comment by johnnyq** [comment] 2021-03-25 20:23
are you using mariaDB or MySQL 8?

**Comment by aftechro** [comment] 2021-03-25 20:46
MariaDB

**Comment by johnnyq** [comment] 2021-04-06 00:04
Hey @aftechro post a data dictionary of the trips table this may help in the trouble shooting

**Comment by johnnyq** [comment] 2023-02-25 02:52
Closing

**Closed by johnnyq** 2023-02-25 02:52 UTC
Labels: bug, enhancement
