### ISSUE TITLE
Feature Request: Ticketing Dashboard

### ISSUE THREAD

**Issue by andrejtr** [itflow-org/itflow#351] opened 2022-02-10 11:56 UTC
Hi there,

TANSS has a cool Dashboard, you can see all activities at a glance.

It would be pretty cool if you guys could implement it into ITFlow!

Image: https://ibb.co/kMjbwgN
Ticketing-Software im reffering to: https://www.tanss.de/en

**Comment by wrongecho** [comment] 2022-12-17 14:45
Some great ideas to work off here, thank you!
Closing as a duplicate of #141.

**Closed by wrongecho** 2022-12-17 14:45 UTC
Labels: duplicate, enhancement
