### ISSUE TITLE
Administrator avatar showing up as the clients avatar for replies in tickets

### ISSUE THREAD

**Issue by sysjohns** [itflow-org/itflow#501] opened 2022-12-09 05:24 UTC
**Describe the bug**
I uploaded my avatar for my Administrator account and that works well, but when I go and check my tickets my client's avatar is now showing my Administrator's avatar for their image. I uploaded the client's avatar which shows up fine under Contacts but soon as you go check their Tickets then it shows up as my Administrator avatar for them. Also when I go to the Client Portal, it shows their image at the top left but not in the replies so I'm thinking that the replies are not pulling the avatar correctly.

**Can you reproduce this on the demo at demo.itflow.org**
Yes

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
Upload a avatar for the admin account under Profile. Then upload a different avatar for a client. Submit a ticket and reply to the ticket. Then check the ticket under Clients/Client Name/Tickets/Ticket Subject Name. The ticket will display the Administrator avatar for all responses.

**Expected behavior**
When we pull up a ticket, we should be able to see different avatar images for the admin and the clients and/or contacts.

**Comment by wrongecho** [comment] 2022-12-11 10:59
Hi there @sysjohns 

Thanks for getting in touch! :)

The cause of this bug is that initially we planned to have a big users table with all techs and client contacts. We soon disocvered this wasn't the best idea so decided to separate out client contacts into it's own database table (as they needed unique fields, etc).

However, as you pointed out, we didn't update the logic for showing the ticket reply avatar - it would always assume it was from an agent. I've adjusted the code so that it checks if the reply type is from a technician or client and then generates the corresponding URL.

Once the PR above is merged, would you mind testing to ensure the issue is resolved?

**Closed** 2022-12-11 18:14 UTC

**Comment by sysjohns** [comment] 2022-12-12 13:53
Your welcome. Thank you for looking into it!

-sysjohns
